spring:
  application:
    name: user-service
  profiles:
    default: docker

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0

  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics,trace
  prometheus:
    metrics:
      export:
        enabled: true
  otlp:
    tracing:
      endpoint: http://otel-collector-opentelemetry-collector.monitoring.svc.cluster.local:4318/v1/traces

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n"
  level:
    root: INFO
